library(tidyr)
library(dplyr)
LIWC_22_Results <- read_csv("LIWC-22 Results.csv")

# Make a new column for doctor/ patient
LIWC_22_Results <- LIWC_22_Results %>% separate(Filename, c('ID', 'Order', 'dr_patient'), sep = "_")
LIWC_22_Results <- LIWC_22_Results %>% separate(dr_patient, 'dr_patient', sep = "[.]")
LIWC_22_Results$order_speaker <- paste(LIWC_22_Results$dr_patient,LIWC_22_Results$Order)

Wide<- as.data.frame(cbind(LIWC_22_Results$ID, LIWC_22_Results$order_speaker, LIWC_22_Results$WC, LIWC_22_Results$Analytic, LIWC_22_Results$Clout, LIWC_22_Results$Authentic, LIWC_22_Results$Tone, LIWC_22_Results$WPS, LIWC_22_Results$BigWords, LIWC_22_Results$Dic, LIWC_22_Results$Linguistic, LIWC_22_Results$`function`, LIWC_22_Results$pronoun, LIWC_22_Results$ppron, LIWC_22_Results$i, LIWC_22_Results$we, LIWC_22_Results$you, LIWC_22_Results$shehe, LIWC_22_Results$they, LIWC_22_Results$ipron, LIWC_22_Results$det, LIWC_22_Results$article, LIWC_22_Results$number, LIWC_22_Results$prep, LIWC_22_Results$auxverb, LIWC_22_Results$adverb, LIWC_22_Results$conj, LIWC_22_Results$negate, LIWC_22_Results$verb, LIWC_22_Results$adj, LIWC_22_Results$quantity, LIWC_22_Results$Drives, LIWC_22_Results$affiliation, LIWC_22_Results$achieve, LIWC_22_Results$power, LIWC_22_Results$Cognition, LIWC_22_Results$allnone, LIWC_22_Results$cogproc, LIWC_22_Results$insight, LIWC_22_Results$cause, LIWC_22_Results$discrep, LIWC_22_Results$tentat, LIWC_22_Results$certitude, LIWC_22_Results$differ, LIWC_22_Results$memory, LIWC_22_Results$Affect, LIWC_22_Results$tone_pos, LIWC_22_Results$tone_neg, LIWC_22_Results$emotion, LIWC_22_Results$emo_pos, LIWC_22_Results$emo_neg, LIWC_22_Results$emo_anx, LIWC_22_Results$emo_anger, LIWC_22_Results$emo_sad, LIWC_22_Results$swear, LIWC_22_Results$Social, LIWC_22_Results$socbehav, LIWC_22_Results$prosocial, LIWC_22_Results$polite, LIWC_22_Results$conflict, LIWC_22_Results$moral, LIWC_22_Results$comm, LIWC_22_Results$socrefs, LIWC_22_Results$family, LIWC_22_Results$friend, LIWC_22_Results$female, LIWC_22_Results$male, LIWC_22_Results$Culture, LIWC_22_Results$politic, LIWC_22_Results$ethnicity, LIWC_22_Results$tech, LIWC_22_Results$Lifestyle, LIWC_22_Results$leisure, LIWC_22_Results$home, LIWC_22_Results$work, LIWC_22_Results$money, LIWC_22_Results$relig, LIWC_22_Results$Physical, LIWC_22_Results$health, LIWC_22_Results$illness, LIWC_22_Results$wellness, LIWC_22_Results$mental, LIWC_22_Results$substances, LIWC_22_Results$sexual, LIWC_22_Results$food, LIWC_22_Results$death, LIWC_22_Results$need, LIWC_22_Results$want, LIWC_22_Results$acquire, LIWC_22_Results$lack, LIWC_22_Results$fulfill, LIWC_22_Results$fatigue, LIWC_22_Results$reward, LIWC_22_Results$risk, LIWC_22_Results$curiosity, LIWC_22_Results$allure, LIWC_22_Results$Perception, LIWC_22_Results$attention, LIWC_22_Results$motion, LIWC_22_Results$space, LIWC_22_Results$visual, LIWC_22_Results$auditory, LIWC_22_Results$feeling, LIWC_22_Results$time, LIWC_22_Results$focuspast, LIWC_22_Results$focuspresent, LIWC_22_Results$focusfuture, LIWC_22_Results$Conversation, LIWC_22_Results$netspeak, LIWC_22_Results$assent, LIWC_22_Results$nonflu, LIWC_22_Results$filler, LIWC_22_Results$AllPunc, LIWC_22_Results$Period, LIWC_22_Results$Comma, LIWC_22_Results$QMark, LIWC_22_Results$Exclam, LIWC_22_Results$Apostro, LIWC_22_Results$OtherP, LIWC_22_Results$Emoji))
colnames(Wide)<-c("ID", "order_speaker", "WC_Exam", "Analytic_Exam", "Clout_Exam", "Authentic_Exam", "Tone_Exam", "WPS_Exam", "BigWords_Exam", "Dic_Exam", "Linguistic_Exam", "function_Exam", "pronoun_Exam", "ppron_Exam", "i_Exam", "we_Exam", "you_Exam", "shehe_Exam", "they_Exam", "ipron_Exam", "det_Exam", "article_Exam", "number_Exam", "prep_Exam", "auxverb_Exam", "adverb_Exam", "conj_Exam", "negate_Exam", "verb_Exam", "adj_Exam", "quantity_Exam", "Drives_Exam", "affiliation_Exam", "achieve_Exam", "power_Exam", "Cognition_Exam", "allnone_Exam", "cogproc_Exam", "insight_Exam", "cause_Exam", "discrep_Exam", "tentat_Exam", "certitude_Exam", "differ_Exam", "memory_Exam", "Affect_Exam", "tone_pos_Exam", "tone_neg_Exam", "emotion_Exam", "emo_pos_Exam", "emo_neg_Exam", "emo_anx_Exam", "emo_anger_Exam", "emo_sad_Exam", "swear_Exam", "social_Exam", "socbehav_Exam", "prosocial_Exam", "polite_Exam", "conflict_Exam", "moral_Exam", "comm_Exam", "socrefs_Exam", "family_Exam", "friend_Exam", "female_Exam", "male_Exam", "culture_Exam", "politic_Exam", "ethnicity_Exam", "tech_Exam", "Lifestyle_Exam", "leisure_Exam", "home_Exam", "work_Exam", "money_Exam", "relig_Exam", "Physical_Exam", "health_Exam", "illness_Exam", "wellness_Exam", "mental_Exam", "substances_Exam", "sexual_Exam", "food_Exam", "death_Exam", "need_Exam", "want_Exam", "acquire_Exam", "lack_Exam", "fulfill_Exam", "fatigue_Exam", "reward_Exam", "risk_Exam", "curiosity_Exam", "allure_Exam", "Perception_Exam", "attention_Exam", "motion_Exam", "space_Exam", "visual_Exam", "auditory_Exam", "feeling_Exam", "time_Exam", "focuspast_Exam", "focuspresent_Exam", "focusfuture_Exam", "Conversation_Exam", "netspeak_Exam", "assent_Exam", "nonflu_Exam", "filler_Exam", "AllPunc_Exam", "Period_Exam", "Comma_Exam", "QMark_Exam", "Exclam_Exam", "Apostro_Exam", "OtherP_Exam", "Emoji_Exam")

LIWC <- Wide %>% 
  pivot_wider( id_cols = "ID",
    names_from  = "order_speaker",
    values_from = c("WC_Exam", "Analytic_Exam", "Clout_Exam", "Authentic_Exam", "Tone_Exam", "WPS_Exam", "BigWords_Exam", "Dic_Exam", "Linguistic_Exam", "function_Exam", "pronoun_Exam", "ppron_Exam", "i_Exam", "we_Exam", "you_Exam", "shehe_Exam", "they_Exam", "ipron_Exam", "det_Exam", "article_Exam", "number_Exam", "prep_Exam", "auxverb_Exam", "adverb_Exam", "conj_Exam", "negate_Exam", "verb_Exam", "adj_Exam", "quantity_Exam", "Drives_Exam", "affiliation_Exam", "achieve_Exam", "power_Exam", "Cognition_Exam", "allnone_Exam", "cogproc_Exam", "insight_Exam", "cause_Exam", "discrep_Exam", "tentat_Exam", "certitude_Exam", "differ_Exam", "memory_Exam", "Affect_Exam", "tone_pos_Exam", "tone_neg_Exam", "emotion_Exam", "emo_pos_Exam", "emo_neg_Exam", "emo_anx_Exam", "emo_anger_Exam", "emo_sad_Exam", "swear_Exam", "social_Exam", "socbehav_Exam", "prosocial_Exam", "polite_Exam", "conflict_Exam", "moral_Exam", "comm_Exam", "socrefs_Exam", "family_Exam", "friend_Exam", "female_Exam", "male_Exam", "culture_Exam", "politic_Exam", "ethnicity_Exam", "tech_Exam", "Lifestyle_Exam", "leisure_Exam", "home_Exam", "work_Exam", "money_Exam", "relig_Exam", "Physical_Exam", "health_Exam", "illness_Exam", "wellness_Exam", "mental_Exam", "substances_Exam", "sexual_Exam", "food_Exam", "death_Exam", "need_Exam", "want_Exam", "acquire_Exam", "lack_Exam", "fulfill_Exam", "fatigue_Exam", "reward_Exam", "risk_Exam", "curiosity_Exam", "allure_Exam", "Perception_Exam", "attention_Exam", "motion_Exam", "space_Exam", "visual_Exam", "auditory_Exam", "feeling_Exam", "time_Exam", "focuspast_Exam", "focuspresent_Exam", "focusfuture_Exam", "Conversation_Exam", "netspeak_Exam", "assent_Exam", "nonflu_Exam", "filler_Exam", "AllPunc_Exam", "Period_Exam", "Comma_Exam", "QMark_Exam", "Exclam_Exam", "Apostro_Exam", "OtherP_Exam", "Emoji_Exam")
  ) %>% 
  print()

#Convert variables in columns to uppercase 
LIWC$ID <- toupper(LIWC$ID)

#Widened results 
write.csv(LIWC, "LIWC_Wide.csv")
