library(tidyr)
library(dplyr)
LIWC_22_Results <- read_csv("LIWC-22 Results.csv")

# Make a new column for doctor/ patient
LIWC_22_Results <- LIWC_22_Results %>% separate(Filename, c('ID', 'Order', 'dr_patient'), sep = "_")
LIWC_22_Results <- LIWC_22_Results %>% separate(dr_patient, 'dr_patient', sep = "[.]")
LIWC_22_Results$speaker_order <- paste(LIWC_22_Results$dr_patient,LIWC_22_Results$Order)

Wide<- as.data.frame(cbind(LIWC_22_Results$ID, LIWC_22_Results$speaker_order, LIWC_22_Results$WC, LIWC_22_Results$Analytic, LIWC_22_Results$Clout, LIWC_22_Results$Authentic, LIWC_22_Results$Tone, LIWC_22_Results$WPS, LIWC_22_Results$BigWords, LIWC_22_Results$Dic, LIWC_22_Results$Linguistic, LIWC_22_Results$`function`, LIWC_22_Results$pronoun, LIWC_22_Results$ppron, LIWC_22_Results$i, LIWC_22_Results$we, LIWC_22_Results$you, LIWC_22_Results$shehe, LIWC_22_Results$they, LIWC_22_Results$ipron, LIWC_22_Results$det, LIWC_22_Results$article, LIWC_22_Results$number, LIWC_22_Results$prep, LIWC_22_Results$auxverb, LIWC_22_Results$adverb, LIWC_22_Results$conj, LIWC_22_Results$negate, LIWC_22_Results$verb, LIWC_22_Results$adj, LIWC_22_Results$quantity, LIWC_22_Results$Drives, LIWC_22_Results$affiliation, LIWC_22_Results$achieve, LIWC_22_Results$power, LIWC_22_Results$Cognition, LIWC_22_Results$allnone, LIWC_22_Results$cogproc, LIWC_22_Results$insight, LIWC_22_Results$cause, LIWC_22_Results$discrep, LIWC_22_Results$tentat, LIWC_22_Results$certitude, LIWC_22_Results$differ, LIWC_22_Results$memory, LIWC_22_Results$Affect, LIWC_22_Results$tone_pos, LIWC_22_Results$tone_neg, LIWC_22_Results$emotion, LIWC_22_Results$emo_pos, LIWC_22_Results$emo_neg, LIWC_22_Results$emo_anx, LIWC_22_Results$emo_anger, LIWC_22_Results$emo_sad, LIWC_22_Results$swear, LIWC_22_Results$Social, LIWC_22_Results$socbehav, LIWC_22_Results$prosocial, LIWC_22_Results$polite, LIWC_22_Results$conflict, LIWC_22_Results$moral, LIWC_22_Results$comm, LIWC_22_Results$socrefs, LIWC_22_Results$family, LIWC_22_Results$friend, LIWC_22_Results$female, LIWC_22_Results$male, LIWC_22_Results$Culture, LIWC_22_Results$politic, LIWC_22_Results$ethnicity, LIWC_22_Results$tech, LIWC_22_Results$Lifestyle, LIWC_22_Results$leisure, LIWC_22_Results$home, LIWC_22_Results$work, LIWC_22_Results$money, LIWC_22_Results$relig, LIWC_22_Results$Physical, LIWC_22_Results$health, LIWC_22_Results$illness, LIWC_22_Results$wellness, LIWC_22_Results$mental, LIWC_22_Results$substances, LIWC_22_Results$sexual, LIWC_22_Results$food, LIWC_22_Results$death, LIWC_22_Results$need, LIWC_22_Results$want, LIWC_22_Results$acquire, LIWC_22_Results$lack, LIWC_22_Results$fulfill, LIWC_22_Results$fatigue, LIWC_22_Results$reward, LIWC_22_Results$risk, LIWC_22_Results$curiosity, LIWC_22_Results$allure, LIWC_22_Results$Perception, LIWC_22_Results$attention, LIWC_22_Results$motion, LIWC_22_Results$space, LIWC_22_Results$visual, LIWC_22_Results$auditory, LIWC_22_Results$feeling, LIWC_22_Results$time, LIWC_22_Results$focuspast, LIWC_22_Results$focuspresent, LIWC_22_Results$focusfuture, LIWC_22_Results$Conversation, LIWC_22_Results$netspeak, LIWC_22_Results$assent, LIWC_22_Results$nonflu, LIWC_22_Results$filler, LIWC_22_Results$AllPunc, LIWC_22_Results$Period, LIWC_22_Results$Comma, LIWC_22_Results$QMark, LIWC_22_Results$Exclam, LIWC_22_Results$Apostro, LIWC_22_Results$OtherP, LIWC_22_Results$Emoji))
colnames(Wide)<-c("ID", "speaker_order", "WC", "Analytic", "Clout", "Authentic", "Tone", "WPS", "BigWords", "Dic", "Linguistic", "function", "pronoun", "ppron", "i", "we", "you", "shehe", "they", "ipron", "det", "article", "number", "prep", "auxverb", "adverb", "conj", "negate", "verb", "adj", "quantity", "Drives", "affiliation", "achieve", "power", "Cognition", "allnone", "cogproc", "insight", "cause", "discrep", "tentat", "certitude", "differ", "memory", "Affect", "tone_pos", "tone_neg", "emotion", "emo_pos", "emo_neg", "emo_anx", "emo_anger", "emo_sad", "swear", "social", "socbehav", "prosocial", "polite", "conflict", "moral", "comm", "socrefs", "family", "friend", "female", "male", "culture", "politic", "ethnicity", "tech", "Lifestyle", "leisure", "home", "work", "money", "relig", "Physical", "health", "illness", "wellness", "mental", "substances", "sexual", "food", "death", "need", "want", "acquire", "lack", "fulfill", "fatigue", "reward", "risk", "curiosity", "allure", "Perception", "attention", "motion", "space", "visual", "auditory", "feeling", "time", "focuspast", "focuspresent", "focusfuture", "Conversation", "netspeak", "assent", "nonflu", "filler", "AllPunc", "Period", "Comma", "QMark", "Exclam", "Apostro", "OtherP", "Emoji") 

LIWC <- Wide %>% 
  pivot_wider( id_cols = "ID",
    names_from  = "speaker_order",
    values_from = c("WC", "Analytic", "Clout", "Authentic", "Tone", "WPS", "BigWords", "Dic", "Linguistic", "function", "pronoun", "ppron", "i", "we", "you", "shehe", "they", "ipron", "det", "article", "number", "prep", "auxverb", "adverb", "conj", "negate", "verb", "adj", "quantity", "Drives", "affiliation", "achieve", "power", "Cognition", "allnone", "cogproc", "insight", "cause", "discrep", "tentat", "certitude", "differ", "memory", "Affect", "tone_pos", "tone_neg", "emotion", "emo_pos", "emo_neg", "emo_anx", "emo_anger", "emo_sad", "swear", "social", "socbehav", "prosocial", "polite", "conflict", "moral", "comm", "socrefs", "family", "friend", "female", "male", "culture", "politic", "ethnicity", "tech", "Lifestyle", "leisure", "home", "work", "money", "relig", "Physical", "health", "illness", "wellness", "mental", "substances", "sexual", "food", "death", "need", "want", "acquire", "lack", "fulfill", "fatigue", "reward", "risk", "curiosity", "allure", "Perception", "attention", "motion", "space", "visual", "auditory", "feeling", "time", "focuspast", "focuspresent", "focusfuture", "Conversation", "netspeak", "assent", "nonflu", "filler", "AllPunc", "Period", "Comma", "QMark", "Exclam", "Apostro", "OtherP", "Emoji")
  ) %>% 
  print()

#Convert variables in columns to uppercase 
LIWC$ID <- toupper(LIWC$ID)

#Widened results 
?write.csv
write.csv(LIWC, "LIWC_Wide.csv")

getwd()
